export const interestLabels = {
  alcohol: 'Alcohol - Drinking',
  anime: 'Anime',
  artGraphics: 'Art/Graphics',
  baking: 'Baking',
  tabletopGames: 'Board/Tabletop Games',
  charity: 'Charity',
  clubbing: 'Clubbing',
  cooking: 'Cooking',
  danceBallroom: 'Dance - Salsa, Ballroom, other partnered dances',
  danceContemporary: 'Dance - Hip hop, urban other contemporary dances',
  dramatics: 'Dramatics - Drama or Musical Theatre',
  film: 'Film and Cinematography',
  finance: 'Finance and Entrepreneurship',
  exerciseAndHealth: 'Fitness and Health',
  hiking: 'Hiking',
  kpop: 'K-pop',
  martialArts: 'Martial Arts and Self Defence',
  performingMusicPopRockJazz: 'Performing Music - Pop, Rock, Jazz',
  performingMusicClassical: 'Performing Music - Classical, Chamber',
  photography: 'Photography',
  politics: 'Politics',
  videoGames: 'Video Games',
  football: 'Football (the British one!)',
  rugby: 'Rugby',
  rowing: 'Rowing',
  racketSports: 'Racket Sports - Tennis, Badminton, other racket sports',
  otherSports: 'Other Sports'
};
