name: release

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag
        run: echo "TAG=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Build and push
        run: |
          docker build -t ghcr.io/icdocsoc/mad3:${{ env.TAG }} .
          docker push ghcr.io/icdocsoc/mad3:${{ env.TAG }}
